// Code generated by "stringer -linecomment -type Token tokens.go"; DO NOT EDIT.

package tokens

import "strconv"

const _Token_name = ".const,;varprocedure:=!?callbeginendifthenwhiledoodd=#<<=>>=+-*/()"

var _Token_index = [...]uint8{0, 1, 6, 7, 8, 11, 20, 22, 23, 24, 28, 33, 36, 38, 42, 47, 49, 52, 53, 54, 55, 57, 58, 60, 61, 62, 63, 64, 65, 66}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
