// Code generated by "stringer -type Token -linecomment"; DO NOT EDIT.

package main

import "strconv"

const _Token_name = "+-*/()"

var _Token_index = [...]uint8{0, 1, 2, 3, 4, 5, 6}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
